<!DOCTYPE html>
<html>
<head>
    <g:set var="entityName" value="${message(code: 'docClass.label', default: 'DocClass')}" />
    <asset:stylesheet src="bootstrap.css"/>
    <asset:stylesheet src="bootstrap-select.css"/>
    <asset:stylesheet src="jquery.timepicker.css"/>
</head>
<body>
<g:if test="${flash.message}">
    <div class="message" role="status">${flash.message}</div>
</g:if>
<g:hasErrors bean="${this.docEnum}">
    <div class="alert alert-warning" role="alert">
        <g:eachError bean="${this.docEnum}" var="error">
            <p <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></p>
        </g:eachError>
    </div>
</g:hasErrors>

<div class="container">
    <div class="card mt-5">
        <div class="card-header">
            <span>${docEnum.name}</span>
            <g:if test="${!docEnum.autoGenerated}">
                <g:link elementId="delete" action="delete" id="${docEnum.id}" class="btn btn-danger float-right">
                    <i class="fas fa-trash"></i>
                    <g:message code="default.button.delete.label" />
                </g:link>
            </g:if>
        </div>
        <div class="card-body">
            <g:form action="update" class="form" useToken="true">
                <div class="row">
                    <g:hiddenField name="id" value="${docEnum?.id}" />
                    <g:hiddenField name="name" value="${docEnum?.name}" />
                    <g:hiddenField name="autoGenerated" value="${docEnum?.autoGenerated}" />

                    <bf:formField bean="${docEnum}" property="description" width="12"/>

                    <g:if test="${!docEnum.autoGenerated}">
                        <div class="form-group col-md-4">
                            <label><g:message code="docEnum.contexts.label"/></label>
                            <g:select multiple="true" name="contexts" from="${org.irblleida.dc.DocClass.findAll()}" optionKey="id" optionValue="name" value="${docEnum?.contexts}" class="form-control"/>
                        </div>
                    </g:if>

                    <g:each var="docEnumValue" in="${docEnum.values}">
                        <div class="col-md-12">
                            <div class="card bg-light mb-3">
                                <div class="card-header">${docEnumValue.name}</div>
                                <div class="card-body">
                                    <div class="row">
                                        <bf:formField bean="${docEnumValue}" property="description" width="12" name="${docEnumValue.name}-description"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </g:each>
                    <div class="col-md-12">
                        <g:submitButton name="create" value="${message(code: 'default.button.update.label')}" class="btn btn-primary" />
                        <g:link controller="dataCatalog" action="index" class="btn btn-secondary">
                            <g:message code="default.button.cancel" />
                        </g:link>
                    </div>
                </div>
            </g:form>
        </div>
    </div>
</div>

<asset:javascript src="jquery-3.3.1.min.js"/>
<asset:javascript src="bootstrap.js"/>
<asset:javascript src="fontawesome-all.js"/>

<g:javascript>
        $(document).on("click", "a.delete", function() {
            if (confirm('<g:message code="default.button.delete.confirm.message" /> ')) {
                return true;
            }
            return false;
        });
</g:javascript>
</body>
</html>
