package org.irblleida.dc

class DocClass {

    String name
    String description
    Boolean autoGenerated

    Boolean getIsCompleted(){
        if (!this.description) return false

        for (variable in this.variables){
            if (!variable.description) return false
        }

        return true
    }

    static hasMany = [
            variables: DocVariable
    ]

    static embedded = ['variables']

    static transients = ['isCompleted']

    static constraints = {
        name nullable: false, blank: false, unique: true
        description nullable: true
        autoGenerated nullable: false
    }
}
