package org.irblleida.dc

class DocEnum {

    String name
    String description
    Boolean autoGenerated

    Boolean getIsCompleted(){
        if (!this.description) return false

        for (value in this.values){
            if (!value.description) return false
        }

        return true
    }

    static hasMany = [
            values: DocEnumValue,
            contexts: DocClass
    ]

    static embedded = ['values']

    static transients = ['isCompleted']

    static constraints = {
        name nullable: false, blank: false, unique: true
        description nullable: true
        autoGenerated nullable: false
    }
}
