package org.irblleida.dc

class DocEnum {

    String name
    String description
    Boolean autoGenerated

    static hasMany = [
            values: DocEnumValue,
            contexts: DocClass
    ]

    static embedded = ['values']

    static constraints = {
        name nullable: false, blank: false, unique: true
        description nullable: true
        autoGenerated nullable: false
    }
}
