<!DOCTYPE html>
<html>
    <head>
        <g:set var="entityName" value="${message(code: 'docClass.label', default: 'DocClass')}" />
        <asset:stylesheet src="bootstrap.css"/>
        <asset:stylesheet src="bootstrap-select.css"/>
        <asset:stylesheet src="jquery.timepicker.css"/>
    </head>
    <body>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.docClass}">
        <div class="alert alert-warning" role="alert">
            <g:eachError bean="${this.docClass}" var="error">
                <p <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></p>
            </g:eachError>
        </div>
    </g:hasErrors>

    <div class="container">
        <div class="card mt-5">
            <div class="card-header">
                <span>${docClass.name}</span>
                <g:link elementId="delete" action="delete" id="${docClass.id}" class="btn btn-danger float-right">
                    <i class="fas fa-trash"></i>
                    <g:message code="default.button.delete.label" />
                </g:link>
            </div>
            <div class="card-body">
                <g:form action="update" class="form" useToken="true">
                    <div class="row">
                        <g:hiddenField name="id" value="${docClass?.id}" />
                        <g:hiddenField name="name" value="${docClass?.name}" />
                        <g:hiddenField name="autoGenerated" value="${docClass?.autoGenerated}" />

                        <bf:formField bean="${docClass}" property="description" width="12"/>

                        <g:each var="docVariable" in="${docClass.variables}">
                            <div class="col-md-12">
                                <div class="card bg-light mb-3">
                                    <div class="card-header">${docVariable.name}</div>
                                    <div class="card-body">
                                        <div class="row">
                                            <bf:formField bean="${docVariable}" property="description" width="12" name="${docVariable.name}-description"/>
                                            <g:if test="${!docVariable.autoGenerated}">
                                                <bf:formField bean="${docVariable}" property="type" width="4" name="${docVariable.name}-type"/>
                                                <bf:formField bean="${docVariable}" property="classType" width="4" name="${docVariable.name}-classType"/>
                                            </g:if>
                                            <bf:formField bean="${docVariable}" property="code" width="4" name="${docVariable.name}-code"/>
                                            <bf:formField bean="${docVariable}" property="required" width="4" name="${docVariable.name}-required"/>
                                            <bf:formField bean="${docVariable}" property="defaultUnits" width="4" name="${docVariable.name}-defaultUnits"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </g:each>
                        <div class="col-md-12">
                            <g:submitButton name="create" value="${message(code: 'default.button.update.label')}" class="btn btn-primary" />
                            <g:link controller="dataCatalog" action="index" class="btn btn-secondary">
                                <g:message code="default.button.cancel" />
                            </g:link>
                        </div>
                    </div>
                </g:form>
            </div>
        </div>
    </div>

    <asset:javascript src="jquery-3.3.1.min.js"/>
    <asset:javascript src="bootstrap.js"/>
    <asset:javascript src="fontawesome-all.js"/>
    <asset:javascript src="jquery.are-you-sure.js"/>
    <g:javascript>
        $(document).on("click", "a.delete", function() {
            if (confirm('<g:message code="default.button.delete.confirm.message" /> ')) {
                return true;
            }
            return false;
        });
    </g:javascript>
    </body>
</html>
