package org.irblleida.dc

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class DocClassController {

    DocClassService docClassService

    def create() {
        respond new DocClass(params)
    }

    def save(DocClass docClass) {
        if (docClass == null) {
            notFound()
            return
        }

        try {
            docClassService.save(docClass)
        } catch (ValidationException e) {
            respond docClass.errors, view:'create'
        }
    }

    def edit(Long id) {
        respond docClassService.get(id)
    }

    def update(DocClass docClass) {

        if (docClass == null) {
            notFound()
            return
        }

        for(DocVariable docVariable in docClass.variables){
            if(params[docVariable.name + '-description']) docVariable.description = params[docVariable.name + '-description']
            if(params[docVariable.name + '-type']) docVariable.type = params[docVariable.name + '-type']
            if(params[docVariable.name + '-classType']) docVariable.classType = params[docVariable.name + '-classType']
            if(params[docVariable.name + '-code']) docVariable.code = params[docVariable.name + '-code']
            if(params[docVariable.name + '-required']) docVariable.required = params[docVariable.name + '-required']
            if(params[docVariable.name + '-defaultUnits']) docVariable.defaultUnits = params[docVariable.name + '-defaultUnits']
        }

        try {
            docClassService.save(docClass)
        } catch (ValidationException e) {
            respond docClass.errors, view:'edit', id: docClass.id.toString()
            return
        }

        flash.message = message(code: 'default.saved.success')
        redirect controller: 'dataCatalog', action: 'index'
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        if(!DocClass.get(id).autoGenerated)
            docClassService.delete(id)
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'docClass.label', default: 'DocClass'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}
